{% set name = "toml-test" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/toml-test/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea14319a926cfd7d418e4b450b47264c478b38ce99280f0cf273c574536e544b

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/BurntSushi/toml-test
  license: MIT
  license_file:
    - COPYING
    - COPYING-toml
    - LICENSE-zli
  summary: A language agnostic test suite for TOML parsers.

extra:
  recipe-maintainers:
    - awvwgk
