{% set name = "toml-test" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/toml-test/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 33bf4e9c017cd57f3602e72d17f75fb5a7bcc7942541c84f1d98b74c12499846

build:
  number: 1

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/BurntSushi/toml-test
  license: MIT
  license_file:
    - COPYING
    - COPYING-toml
    - LICENSE-zli
  summary: A language agnostic test suite for TOML parsers.

extra:
  recipe-maintainers:
    - awvwgk
