{% set name = "toml-test" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/toml-test/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 41d5a748b6942e535c43fc6d8a12ea7ecb6b24cb8bbe09adf929364099407741

build:
  number: 1

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/BurntSushi/toml-test
  license: MIT
  license_file:
    - COPYING
    - COPYING-toml
    - LICENSE-zli
  summary: A language agnostic test suite for TOML parsers.

extra:
  recipe-maintainers:
    - awvwgk
