{% set name = "toml-test" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/toml-test/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 737604b374669975fd8d80c562124e2ff4913217aeadbb14ff07033c52fe09ac

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/BurntSushi/toml-test
  license: MIT
  license_file:
    - COPYING
    - COPYING-toml
    - LICENSE-zli
  summary: A language agnostic test suite for TOML parsers.

extra:
  recipe-maintainers:
    - awvwgk
