{% set name = "toml-test" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/toml-test/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e6829cdcaed94ac2bfcaea05dab9d16db0bead2d3ac9936224774a67fbd46ade

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/BurntSushi/toml-test
  license: MIT
  license_file:
    - COPYING
    - COPYING-toml
    - LICENSE-zli
  summary: A language agnostic test suite for TOML parsers.

extra:
  recipe-maintainers:
    - awvwgk
